name: ci/cd

on:
  push:
    branches: ["main"]

env:
  image1: ghcr.io/${{ github.repository_owner }}/go-app

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t $image1:latest .

      - name: Scan image
        uses: aquasecurity/trivy-action@0.28.1
        with:
          image-ref: "${{ env.image1 }}:latest"
          severity: "CRITICAL,HIGH"
          exit-code: "1"
