name: ci/cd

on:
  push:
    branches: ["main"]

env:
  image1: ghcr.io/${{ github.repository_owner }}/go-app

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build and unit test
        run: go build -o app && go test ./...

      - name: go vet
        run: go vet ./...

      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with: 
         version: latest

      - name: Build docker image
        run: docker build -t $image1:latest .

      - name: Scan image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          version: 'v0.69.3'
          scan-type: 'image'
          image-ref: "${{ env.image1 }}:latest"
          severity: "CRITICAL,HIGH"
          exit-code: "1"
          mode: client
        continue-on-error: true
